version: "3.7"
services:
  app:
    build:
      args:
        user: shane
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: to-do-list
    container_name: to-do-list-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - to-do-list

  db:
    image: postgres:12-alpine
    container_name: to-do-list-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    networks:
      - to-do-list

  nginx:
    image: nginx:alpine
    container_name: to-do-list-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - to-do-list

networks:
  to-do-list:
    driver: bridge